spring:
  datasource:
    url: jdbc:sqlite:/app/addressbook.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLiteDialect

server:
  port: 8080