spring:
  datasource:
    url: jdbc:mysql://localhost:3306/addressbook?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 690608
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # ??? ?????validate ? update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8080